#!/bin/bash

export CONTAINER_VERSION=v2024.03.26

MSGFPLUS_VERSION=v20240326
DOWNLOAD_URL="https://github.com/MSGFPlus/msgfplus/releases/download/${CONTAINER_VERSION}/MSGFPlus_${MSGFPLUS_VERSION}.zip"

export CONTAINER_BUILD_ARGS="--build-arg DOWNLOAD_URL=${DOWNLOAD_URL}"
