#!/bin/bash

export CONTAINER_VERSION=2.0.2.2

MIXMHC2PRED_VERSION=v2.0.2.2
MIXMHC2PRED_SHORTVERSION=2.0

DOWNLOAD_URL=https://github.com/GfellerLab/MixMHC2pred/releases/download/${MIXMHC2PRED_VERSION}/MixMHC2pred-${MIXMHC2PRED_SHORTVERSION}.zip

export CONTAINER_BUILD_ARGS="--build-arg DOWNLOAD_URL=${DOWNLOAD_URL}"
