name: Docker build and push to quay

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ "published" ]

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
            registry: quay.io
            username: ${{ secrets.QUAY_BOT_NAME }}
            password: ${{ secrets.QUAY_BOT_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
            context: docker/
            file: docker/comet/Dockerfile
            push: true
            tags: quay.io/medbioinf/comet-ms:dev

