name: Docker build and push to quay

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ "published" ]

env:
  REGISTRY: quay.io

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
            registry: ${{ env.REGISTRY }}            
            username: ${{ secrets.QUAY_BOT_NAME }}
            password: ${{ secrets.QUAY_BOT_PASS }}

      - name: Build and push
        run: |
          ./build.sh ${{ secrets.QUAY_API_KEY }}
